# Generated by Django 5.1.15 on 2026-05-29 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0043_organizer_identity_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerPolicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.TextField(blank=True)),
                ('refund_policy', models.TextField(blank=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_policies', to='organizers.organizer')),
            ],
            options={
                'ordering': ['organizer__name', 'id'],
            },
        ),
    ]
