# Generated by Django 5.1.15 on 2026-05-29 14:10

import django.db.models.deletion
import organizer_media.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0043_organizer_identity_whatsapp_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerMediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=255, upload_to=organizer_media.models.organizer_media_upload_path)),
                ('storage_key', models.CharField(default=organizer_media.models.organizer_media_storage_key, max_length=48, unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=240)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=1)),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('alt_text', models.CharField(blank=True, max_length=220)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_media_items', to='organizers.organizer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_organizer_media_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='organizer_media_item_position_must_be_positive')],
            },
        ),
    ]
