# Generated by Django 5.1 for TripOS issue 03.

import django.db.models.deletion
from django.db import migrations, models


def create_payment_setup_records(apps, schema_editor):
    Organizer = apps.get_model("organizers", "Organizer")
    PayoutAccount = apps.get_model("organizers", "PayoutAccount")
    ProviderPaymentSetup = apps.get_model("organizers", "ProviderPaymentSetup")

    for organizer in Organizer.objects.all().iterator():
        PayoutAccount.objects.get_or_create(organizer=organizer)
        ProviderPaymentSetup.objects.get_or_create(organizer=organizer)


class Migration(migrations.Migration):
    dependencies = [
        ("organizers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("holder_name", models.CharField(blank=True, max_length=160)),
                ("provider_account_reference", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("action_required", "Action required"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_account",
                        to="organizers.organizer",
                    ),
                ),
            ],
            options={
                "ordering": ["organizer__name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProviderPaymentSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("razorpay", "Razorpay")],
                        default="razorpay",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("action_required", "Action required"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                ("provider_merchant_reference", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_payment_setup",
                        to="organizers.organizer",
                    ),
                ),
            ],
            options={
                "ordering": ["organizer__name", "id"],
            },
        ),
        migrations.RunPython(create_payment_setup_records, migrations.RunPython.noop),
    ]
