# Generated by Django 5.1.15 on 2026-05-21 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizers", "0010_manual_bookings_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("notification_sent", "Notification Sent"),
                    (
                        "sensitive_traveler_information_download",
                        "Sensitive Traveler Information Download",
                    ),
                    ("traveler_document_approved", "Traveler Document Approved"),
                    ("traveler_document_rejected", "Traveler Document Rejected"),
                ],
                max_length=80,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            (
                                "reservation_acknowledgement",
                                "Reservation Acknowledgement",
                            ),
                            ("confirmation_notice", "Confirmation Notice"),
                            (
                                "payment_acknowledgement",
                                "Payment Acknowledgement",
                            ),
                            ("refund_acknowledgement", "Refund Acknowledgement"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("email", "Email")],
                        max_length=16,
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("booking_contact", "Booking Contact"),
                            ("traveler", "Traveler"),
                        ],
                        max_length=24,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=160)),
                ("recipient_phone", models.CharField(blank=True, max_length=40)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("organizer_identity_name", models.CharField(max_length=160)),
                ("organizer_identity_logo_url", models.URLField(blank=True)),
                ("subject", models.CharField(max_length=180)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent")],
                        default="sent",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=220, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organizers.booking",
                    ),
                ),
                (
                    "manual_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="organizers.manualpayment",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organizers.organizer",
                    ),
                ),
                (
                    "provider_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="organizers.providerpayment",
                    ),
                ),
                (
                    "traveler_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organizers.travelerslot",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organizers.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at", "-id"],
            },
        ),
    ]
