# Generated by Django 5.1.15 on 2026-05-21 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0012_booking_adjustments_refund_records"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="travelerslot",
            name="attendance_marked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="travelerslot",
            name="attendance_marked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_traveler_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="travelerslot",
            name="attendance_state",
            field=models.CharField(
                choices=[
                    ("not_marked", "Not marked"),
                    ("checked_in", "Checked in"),
                    ("no_show", "No-show"),
                ],
                default="not_marked",
                max_length=24,
            ),
        ),
    ]
