# Generated by Django 5.1.15 on 2026-05-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_booked_traveler_slot_amounts(apps, schema_editor):
    TravelerSlot = apps.get_model("organizers", "TravelerSlot")
    for traveler_slot in TravelerSlot.objects.select_related("package").all():
        traveler_slot.booked_package_price_inr = traveler_slot.package.price_inr
        traveler_slot.booked_reservation_amount_inr = traveler_slot.package.reservation_amount_inr
        traveler_slot.save(
            update_fields=[
                "booked_package_price_inr",
                "booked_reservation_amount_inr",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0013_travelerslot_attendance_marked_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="travelerslot",
            name="addition_reserved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="travelerslot",
            name="booked_package_price_inr",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="travelerslot",
            name="booked_reservation_amount_inr",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="travelerslot",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="travelerslot",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="travelerslot",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_traveler_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="travelerslot",
            name="replaced_by_slot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaces_slot",
                to="organizers.travelerslot",
            ),
        ),
        migrations.AddField(
            model_name="travelerslot",
            name="traveler_state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("replaced", "Replaced"),
                    ("pending_addition", "Pending Addition"),
                ],
                default="active",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            populate_booked_traveler_slot_amounts,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("notification_sent", "Notification Sent"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("traveler_cancelled", "Traveler Cancelled"),
                    ("traveler_replaced", "Traveler Replaced"),
                    ("traveler_addition_created", "Traveler Addition Created"),
                    ("traveler_addition_reserved", "Traveler Addition Reserved"),
                    ("traveler_package_changed", "Traveler Package Changed"),
                    ("booking_adjustment_recorded", "Booking Adjustment Recorded"),
                    ("refund_record_recorded", "Refund Record Recorded"),
                    ("traveler_checked_in", "Traveler Checked In"),
                    ("traveler_marked_no_show", "Traveler Marked No-Show"),
                    (
                        "sensitive_traveler_information_download",
                        "Sensitive Traveler Information Download",
                    ),
                    (
                        "sensitive_payment_information_download",
                        "Sensitive Payment Information Download",
                    ),
                    ("traveler_document_approved", "Traveler Document Approved"),
                    ("traveler_document_rejected", "Traveler Document Rejected"),
                ],
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("provider_payment", "Provider Payment"),
                    ("approved_manual_payment", "Approved Manual Payment"),
                    ("opening_payment_record", "Opening Payment Record"),
                    ("booking_adjustment", "Booking Adjustment"),
                    ("package_change", "Package Change"),
                    ("refund_record", "Refund Record"),
                    ("platform_fee", "Platform Fee"),
                ],
                max_length=40,
            ),
        ),
    ]
