# Generated by Django 5.1.15 on 2026-05-21 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizers", "0015_operational_export"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("completed_with_conflicts", "Completed with conflicts"),
                        ],
                        default="completed",
                        max_length=32,
                    ),
                ),
                ("source_filename", models.CharField(blank=True, max_length=240)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("conflict_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_booking_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_imports",
                        to="organizers.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BookingImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("skipped", "Skipped"),
                            ("conflict", "Conflict"),
                        ],
                        max_length=16,
                    ),
                ),
                ("conflict_code", models.CharField(blank=True, max_length=80)),
                ("message", models.CharField(blank=True, max_length=240)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_rows",
                        to="organizers.booking",
                    ),
                ),
                (
                    "booking_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="organizers.bookingimport",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="OpeningPaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount_inr", models.PositiveIntegerField()),
                ("payment_reference", models.CharField(blank=True, max_length=160)),
                ("note", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_payment_records",
                        to="organizers.booking",
                    ),
                ),
                (
                    "booking_import",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opening_payment_records",
                        to="organizers.bookingimport",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_opening_payment_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="opening_payment_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="organizers.openingpaymentrecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("opening_payment_record__isnull", False)),
                fields=("opening_payment_record", "entry_type"),
                name="unique_opening_payment_record_ledger_entry_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingimportrow",
            constraint=models.UniqueConstraint(
                fields=("booking_import", "row_number"), name="unique_booking_import_row_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="openingpaymentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_inr__gt", 0)),
                name="opening_payment_record_amount_must_be_positive",
            ),
        ),
    ]
