# Generated by Django 5.1.15 on 2026-05-25 18:56

from django.db import migrations, models


def supersede_duplicate_active_payment_attempts(apps, schema_editor):
    PaymentAttempt = apps.get_model("organizers", "PaymentAttempt")

    duplicate_keys = (
        PaymentAttempt.objects.filter(status__in=["pending", "confirming"])
        .values("booking_id", "purpose")
        .annotate(active_count=models.Count("id"))
        .filter(active_count__gt=1)
    )

    for duplicate in duplicate_keys:
        active_attempt_ids = list(
            PaymentAttempt.objects.filter(
                booking_id=duplicate["booking_id"],
                purpose=duplicate["purpose"],
                status__in=["pending", "confirming"],
            )
            .order_by("-created_at", "-id")
            .values_list("id", flat=True)
        )
        PaymentAttempt.objects.filter(id__in=active_attempt_ids[1:]).update(
            status="superseded",
            failure_reason="Superseded by a newer Payment Attempt.",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0023_seat_holds'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='checkout_succeeded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='purpose',
            field=models.CharField(choices=[('reservation', 'Reservation'), ('balance', 'Balance')], default='reservation', max_length=24),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='pending', max_length=24),
        ),
        migrations.RunPython(
            supersede_duplicate_active_payment_attempts,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirming'])), fields=('booking', 'purpose'), name='unique_active_payment_attempt_per_booking_purpose'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_attempt_reference', ''), _negated=True), fields=('provider', 'provider_attempt_reference'), name='unique_provider_attempt_reference_per_provider'),
        ),
    ]
