# Generated by Django 5.1.15 on 2026-05-25 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0024_payment_attempt_lifecycle_checkout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('notification_sent', 'Notification Sent'), ('booking_cancelled', 'Booking Cancelled'), ('traveler_cancelled', 'Traveler Cancelled'), ('traveler_replaced', 'Traveler Replaced'), ('traveler_addition_created', 'Traveler Addition Created'), ('traveler_addition_reserved', 'Traveler Addition Reserved'), ('traveler_package_changed', 'Traveler Package Changed'), ('booking_adjustment_recorded', 'Booking Adjustment Recorded'), ('refund_record_recorded', 'Refund Record Recorded'), ('payment_exception_created', 'Payment Exception Created'), ('payment_exception_resolved', 'Payment Exception Resolved'), ('traveler_checked_in', 'Traveler Checked In'), ('traveler_marked_no_show', 'Traveler Marked No-Show'), ('sensitive_traveler_information_download', 'Sensitive Traveler Information Download'), ('sensitive_payment_information_download', 'Sensitive Payment Information Download'), ('traveler_document_approved', 'Traveler Document Approved'), ('traveler_document_rejected', 'Traveler Document Rejected'), ('operational_export_generated', 'Operational Export Generated'), ('trip_duplicated', 'Trip Duplicated'), ('trip_date_changed', 'Trip Date Changed'), ('trip_cancelled', 'Trip Cancelled'), ('trip_completed', 'Trip Completed'), ('booking_completed', 'Booking Completed')], max_length=80),
        ),
        migrations.CreateModel(
            name='PaymentException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('late_confirmed_payment', 'Late Confirmed Payment Exception'), ('mismatched_provider_payment', 'Mismatched Provider Payment Exception'), ('provider_dispute', 'Provider Dispute Exception')], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('booking_operations_resolved', 'Booking Operations Resolved')], default='open', max_length=40)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('amount_inr', models.PositiveIntegerField()),
                ('provider_attempt_reference', models.CharField(blank=True, max_length=160)),
                ('provider_payment_reference', models.CharField(blank=True, max_length=160)),
                ('provider_event_type', models.CharField(blank=True, choices=[('dispute', 'Dispute'), ('chargeback', 'Chargeback')], max_length=32)),
                ('provider_dispute_reference', models.CharField(blank=True, max_length=160)),
                ('mismatch_reasons', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_exceptions', to='organizers.booking')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_exceptions', to='organizers.organizer')),
                ('payment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_exceptions', to='organizers.paymentattempt')),
                ('provider_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_exceptions', to='organizers.providerpayment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_payment_exceptions', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_exceptions', to='organizers.trip')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_inr__gt', 0)), name='payment_exception_amount_must_be_positive'), models.UniqueConstraint(condition=models.Q(('provider_payment_reference', ''), _negated=True), fields=('exception_type', 'provider', 'provider_payment_reference'), name='unique_payment_exception_provider_reference'), models.UniqueConstraint(condition=models.Q(('provider_dispute_reference', ''), _negated=True), fields=('exception_type', 'provider_dispute_reference'), name='unique_payment_exception_dispute_reference'), models.UniqueConstraint(condition=models.Q(('provider_payment__isnull', False)), fields=('exception_type', 'provider_payment'), name='unique_payment_exception_provider_payment')],
            },
        ),
    ]
