# Generated by Django 5.1.15 on 2026-05-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0025_alter_activitylog_action_paymentexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpayment',
            name='provider_fee_amount_inr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerpayment',
            name='provider_net_settlement_amount_inr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
