# Generated by Django 5.1.15 on 2026-05-26 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0026_providerpayment_provider_fee_amount_inr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('provider_payment_count', models.PositiveIntegerField(default=0)),
                ('gross_provider_payment_amount_inr', models.PositiveIntegerField(default=0)),
                ('platform_fee_amount_inr', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('collected', 'Collected'), ('void', 'Void')], default='draft', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_fee_statements', to='organizers.organizer')),
            ],
            options={
                'ordering': ['-period_start', 'organizer__name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('currency', 'INR')), name='platform_fee_statement_currency_must_be_inr'), models.UniqueConstraint(fields=('organizer', 'period_start'), name='unique_platform_fee_statement_organizer_period')],
            },
        ),
    ]
