# Generated by Django 5.1.15 on 2026-05-26 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizers", "0027_platformfeestatement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveProviderCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("razorpay", "Razorpay")], default="razorpay", max_length=32
                    ),
                ),
                (
                    "provider_mode",
                    models.CharField(
                        choices=[("test", "Test"), ("live", "Live")], default="test", max_length=12
                    ),
                ),
                (
                    "credential_kind",
                    models.CharField(
                        choices=[
                            ("oauth", "OAuth Provider Authorization"),
                            ("api_key", "API Key Provider Authorization"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("rotated", "Rotated"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                ("provider_account_reference", models.CharField(blank=True, max_length=160)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("encrypted_payload", models.TextField()),
                ("encryption_key_id", models.CharField(max_length=80)),
                ("credential_fingerprint", models.CharField(max_length=96)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sensitive_provider_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitive_provider_credentials",
                        to="organizers.organizer",
                    ),
                ),
                (
                    "provider_payment_setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitive_credentials",
                        to="organizers.providerpaymentsetup",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_sensitive_provider_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rotated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rotated_sensitive_provider_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organizer__name", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SensitiveProviderCredentialAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("stored", "Stored"),
                            ("retrieved", "Retrieved"),
                            ("rotated", "Rotated"),
                            ("revoked", "Revoked"),
                        ],
                        max_length=24,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sensitive_provider_credential_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="organizers.sensitiveprovidercredential",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitive_provider_credential_audits",
                        to="organizers.organizer",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="sensitiveprovidercredential",
            index=models.Index(
                fields=["organizer", "provider", "provider_mode", "status"],
                name="cred_active_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="sensitiveprovidercredential",
            index=models.Index(
                fields=["provider", "provider_account_reference"], name="cred_provider_acct_lookup"
            ),
        ),
        migrations.AddConstraint(
            model_name="sensitiveprovidercredential",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("organizer", "provider", "provider_mode"),
                name="unique_active_sensitive_provider_credential",
            ),
        ),
        migrations.AddIndex(
            model_name="sensitiveprovidercredentialaudit",
            index=models.Index(
                fields=["organizer", "event_type", "occurred_at"], name="cred_audit_event_lookup"
            ),
        ),
    ]
