# Generated by Codex on 2026-05-28

import django.db.models.deletion
import organizers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizers", "0038_trip_confirmation_requirements_reviewed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripMediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        max_length=255,
                        upload_to=organizers.models.trip_media_asset_upload_path,
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(
                        default=organizers.models.trip_media_storage_key,
                        max_length=48,
                        unique=True,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=240)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_media_assets",
                        to="organizers.organizer",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_trip_media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_for_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_media_assets",
                        to="organizers.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TripMediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=1)),
                ("caption", models.CharField(blank=True, max_length=220)),
                ("alt_text", models.CharField(blank=True, max_length=220)),
                ("is_public", models.BooleanField(default=False)),
                ("is_cover", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_items",
                        to="organizers.tripmediaasset",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="organizers.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="tripmediaitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gt", 0)),
                name="trip_media_item_position_must_be_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tripmediaitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cover", True)),
                fields=("trip",),
                name="unique_cover_trip_media_item_per_trip",
            ),
        ),
    ]
