# Generated by Codex on 2026-05-29

import organizers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizers", "0040_alter_activitylog_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualPaymentInstructions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_qr",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to=organizers.models.payment_qr_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=240)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("upi_id", models.CharField(blank=True, max_length=80)),
                ("account_name", models.CharField(blank=True, max_length=160)),
                ("bank_transfer_details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="manual_payment_instructions",
                        to="organizers.organizer",
                    ),
                ),
            ],
            options={
                "ordering": ["organizer__name", "id"],
            },
        ),
    ]
