# Generated by Django 5.1.15 on 2026-05-29 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0043_organizer_identity_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_choice', models.CharField(choices=[('tripos_default', 'TripOS default'), ('fast_draft', 'Fast draft'), ('high_detail', 'High detail')], default='tripos_default', max_length=32)),
                ('brand_tone', models.CharField(blank=True, max_length=240)),
                ('default_style', models.CharField(blank=True, max_length=240)),
                ('logo_usage', models.CharField(choices=[('use_when_available', 'Use when available'), ('avoid_by_default', 'Avoid by default'), ('never_use', 'Never use')], default='use_when_available', max_length=32)),
                ('poster_defaults', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creative_setup', to='organizers.organizer')),
            ],
            options={
                'ordering': ['organizer__name', 'id'],
            },
        ),
    ]
