from django.urls import path

from organizers.views import (
    CurrentSessionView,
    InternalAdminAssistedPaymentSetupView,
    InternalAdminBookingDetailView,
    InternalAdminOrganizerDetailView,
    InternalAdminOrganizerListView,
    InternalAdminProviderConnectionTestListCreateView,
    InternalAdminSettlementReadinessConfirmView,
    InternalAdminTripDetailView,
    LoginView,
    LogoutView,
    ManualPaymentInstructionsView,
    OperationsAnnouncementCreateView,
    OperationsBalancePaymentLinkSendView,
    OperationsBookingAccessLinkIssueView,
    OperationsBookingAdjustmentCreateView,
    OperationsBookingCancellationView,
    OperationsBookingConfirmView,
    OperationsBookingDetailView,
    OperationsBookingImportCreateView,
    OperationsBookingUnconfirmView,
    OperationsDashboardView,
    OperationsManualBookingCreateView,
    OperationsManualPaymentApproveView,
    OperationsManualPaymentCreateView,
    OperationsManualPaymentProofDownloadView,
    OperationsManualPaymentRejectView,
    OperationsManualReminderCreateView,
    OperationsPaymentExceptionResolveView,
    OperationsRefundRecordCreateView,
    OperationsTravelerAdditionView,
    OperationsTravelerCancellationView,
    OperationsTravelerCheckInView,
    OperationsTravelerDocumentDownloadView,
    OperationsTravelerDocumentListView,
    OperationsTravelerDocumentReviewView,
    OperationsTravelerNoShowView,
    OperationsTravelerPackageChangeView,
    OperationsTravelerReplacementView,
    OperationsTripOperationalExportView,
    OperationsTripOverviewView,
    OperatorWorkflowAccessView,
    OrganizerIdentityView,
    OrganizerInvitationAcceptView,
    OrganizerInvitationResendView,
    OrganizerInvitationRevokeView,
    OrganizerMediaLibraryView,
    OrganizerOnboardingView,
    OrganizerTeamAccessView,
    PaymentSetupStatusView,
    PayoutAccountView,
    ProviderAccountReplacementConfirmView,
    ProviderAuthorizationCallbackView,
    ProviderAuthorizationDisconnectView,
    ProviderAuthorizationStartView,
    ProviderConnectionTestListCreateView,
    ProviderPaymentConfirmationView,
    ProviderPaymentSetupView,
    PublicBookingReadinessView,
    PublicDraftBookingCreateView,
    PublicPaymentAttemptCheckoutSuccessView,
    PublicPaymentAttemptCreateView,
    PublicQrManualPaymentSubmissionView,
    PublicTripBookingReadinessView,
    PublicTripDetailView,
    RazorpayWebhookView,
    SignupView,
    TravelerPortalBalancePaymentAttemptCreateView,
    TravelerPortalDetailView,
    TravelerPortalEmergencyContactView,
    TravelerPortalManualPaymentSubmissionView,
    TravelerPortalMedicalDisclosureView,
    TravelerPortalTravelerDocumentSubmissionView,
    TravelerPortalTravelerIdentityView,
    TravelerPortalTravelLogisticsView,
    TripCancellationView,
    TripCompletionView,
    TripConfirmationRequirementsSectionView,
    TripDateChangeView,
    TripDescriptionView,
    TripDuplicateView,
    TripItineraryView,
    TripMediaGalleryView,
    TripPackageSectionView,
    TripPaymentScheduleSectionView,
    TripSetupDetailView,
    TripSetupListCreateView,
)

urlpatterns = [
    path("auth/signup/", SignupView.as_view(), name="auth-signup"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/session/", CurrentSessionView.as_view(), name="auth-session"),
    path(
        "onboarding/organizer/",
        OrganizerOnboardingView.as_view(),
        name="organizer-onboarding",
    ),
    path(
        "internal-admin/organizers/",
        InternalAdminOrganizerListView.as_view(),
        name="internal-admin-organizer-list",
    ),
    path(
        "internal-admin/organizers/<int:organizer_id>/",
        InternalAdminOrganizerDetailView.as_view(),
        name="internal-admin-organizer-detail",
    ),
    path(
        "internal-admin/organizers/<int:organizer_id>/assisted-payment-setup/",
        InternalAdminAssistedPaymentSetupView.as_view(),
        name="internal-admin-assisted-payment-setup",
    ),
    path(
        "internal-admin/organizers/<int:organizer_id>/settlement-readiness/confirm/",
        InternalAdminSettlementReadinessConfirmView.as_view(),
        name="internal-admin-settlement-readiness-confirm",
    ),
    path(
        "internal-admin/organizers/<int:organizer_id>/provider-connection-tests/",
        InternalAdminProviderConnectionTestListCreateView.as_view(),
        name="internal-admin-provider-connection-tests",
    ),
    path(
        "internal-admin/trips/<int:trip_id>/",
        InternalAdminTripDetailView.as_view(),
        name="internal-admin-trip-detail",
    ),
    path(
        "internal-admin/bookings/<int:booking_id>/",
        InternalAdminBookingDetailView.as_view(),
        name="internal-admin-booking-detail",
    ),
    path("operations/dashboard/", OperationsDashboardView.as_view(), name="operations-dashboard"),
    path(
        "operations/organizers/<int:organizer_id>/operator-workflow-access/",
        OperatorWorkflowAccessView.as_view(),
        name="operator-workflow-access",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/",
        OperationsBookingDetailView.as_view(),
        name="operations-booking-detail",
    ),
    path(
        "operations/organizers/<int:organizer_id>/trips/<int:trip_id>/manual-bookings/",
        OperationsManualBookingCreateView.as_view(),
        name="operations-manual-booking-create",
    ),
    path(
        "operations/organizers/<int:organizer_id>/trips/<int:trip_id>/overview/",
        OperationsTripOverviewView.as_view(),
        name="operations-trip-overview",
    ),
    path(
        "operations/organizers/<int:organizer_id>/trips/<int:trip_id>/booking-imports/",
        OperationsBookingImportCreateView.as_view(),
        name="operations-booking-import-create",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/manual-reminders/",
        OperationsManualReminderCreateView.as_view(),
        name="operations-manual-reminder-create",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/balance-payment-links/",
        OperationsBalancePaymentLinkSendView.as_view(),
        name="operations-balance-payment-link-send",
    ),
    path(
        "operations/organizers/<int:organizer_id>/trips/<int:trip_id>/announcements/",
        OperationsAnnouncementCreateView.as_view(),
        name="operations-announcement-create",
    ),
    path(
        "operations/organizers/<int:organizer_id>/trips/<int:trip_id>/operational-export.csv",
        OperationsTripOperationalExportView.as_view(),
        name="operations-trip-operational-export",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/manual-payments/",
        OperationsManualPaymentCreateView.as_view(),
        name="operations-manual-payment-create",
    ),
    path(
        "operations/organizers/<int:organizer_id>/manual-payments/<int:manual_payment_id>/approve/",
        OperationsManualPaymentApproveView.as_view(),
        name="operations-manual-payment-approve",
    ),
    path(
        "operations/organizers/<int:organizer_id>/manual-payments/<int:manual_payment_id>/reject/",
        OperationsManualPaymentRejectView.as_view(),
        name="operations-manual-payment-reject",
    ),
    path(
        "operations/organizers/<int:organizer_id>/manual-payments/<int:manual_payment_id>/proof-download/",
        OperationsManualPaymentProofDownloadView.as_view(),
        name="operations-manual-payment-proof-download",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/adjustments/",
        OperationsBookingAdjustmentCreateView.as_view(),
        name="operations-booking-adjustment-create",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/refund-records/",
        OperationsRefundRecordCreateView.as_view(),
        name="operations-refund-record-create",
    ),
    path(
        "operations/organizers/<int:organizer_id>/payment-exceptions/<int:payment_exception_id>/resolve/",
        OperationsPaymentExceptionResolveView.as_view(),
        name="operations-payment-exception-resolve",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/cancel/",
        OperationsBookingCancellationView.as_view(),
        name="operations-booking-cancel",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/traveler-additions/",
        OperationsTravelerAdditionView.as_view(),
        name="operations-traveler-addition",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/confirm/",
        OperationsBookingConfirmView.as_view(),
        name="operations-booking-confirm",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/unconfirm/",
        OperationsBookingUnconfirmView.as_view(),
        name="operations-booking-unconfirm",
    ),
    path(
        "operations/organizers/<int:organizer_id>/traveler-slots/<int:traveler_slot_id>/check-in/",
        OperationsTravelerCheckInView.as_view(),
        name="operations-traveler-check-in",
    ),
    path(
        "operations/organizers/<int:organizer_id>/traveler-slots/<int:traveler_slot_id>/no-show/",
        OperationsTravelerNoShowView.as_view(),
        name="operations-traveler-no-show",
    ),
    path(
        "operations/organizers/<int:organizer_id>/traveler-slots/<int:traveler_slot_id>/cancel/",
        OperationsTravelerCancellationView.as_view(),
        name="operations-traveler-cancel",
    ),
    path(
        "operations/organizers/<int:organizer_id>/traveler-slots/<int:traveler_slot_id>/replace/",
        OperationsTravelerReplacementView.as_view(),
        name="operations-traveler-replace",
    ),
    path(
        "operations/organizers/<int:organizer_id>/traveler-slots/<int:traveler_slot_id>/package/",
        OperationsTravelerPackageChangeView.as_view(),
        name="operations-traveler-package-change",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/access-links/",
        OperationsBookingAccessLinkIssueView.as_view(),
        name="operations-booking-access-link-issue",
    ),
    path(
        "operations/organizers/<int:organizer_id>/bookings/<int:booking_id>/traveler-documents/",
        OperationsTravelerDocumentListView.as_view(),
        name="operations-traveler-document-list",
    ),
    path(
        "operations/organizers/<int:organizer_id>/traveler-documents/<int:document_id>/",
        OperationsTravelerDocumentReviewView.as_view(),
        name="operations-traveler-document-review",
    ),
    path(
        "operations/organizers/<int:organizer_id>/traveler-documents/<int:document_id>/download/",
        OperationsTravelerDocumentDownloadView.as_view(),
        name="operations-traveler-document-download",
    ),
    path(
        "organizers/<int:organizer_id>/identity/",
        OrganizerIdentityView.as_view(),
        name="organizer-identity",
    ),
    path(
        "organizers/<int:organizer_id>/media/",
        OrganizerMediaLibraryView.as_view(),
        name="organizer-media",
    ),
    path(
        "organizers/<int:organizer_id>/team-access/",
        OrganizerTeamAccessView.as_view(),
        name="organizer-team-access",
    ),
    path(
        "organizers/<int:organizer_id>/team-access/invitations/<int:invitation_id>/resend/",
        OrganizerInvitationResendView.as_view(),
        name="organizer-invitation-resend",
    ),
    path(
        "organizers/<int:organizer_id>/team-access/invitations/<int:invitation_id>/revoke/",
        OrganizerInvitationRevokeView.as_view(),
        name="organizer-invitation-revoke",
    ),
    path(
        "organizer-invitations/<str:token>/",
        OrganizerInvitationAcceptView.as_view(),
        name="organizer-invitation-accept",
    ),
    path(
        "organizers/<int:organizer_id>/payout-account/",
        PayoutAccountView.as_view(),
        name="organizer-payout-account",
    ),
    path(
        "organizers/<int:organizer_id>/provider-payment-setup/",
        ProviderPaymentSetupView.as_view(),
        name="organizer-provider-payment-setup",
    ),
    path(
        "organizers/<int:organizer_id>/manual-payment-instructions/",
        ManualPaymentInstructionsView.as_view(),
        name="organizer-manual-payment-instructions",
    ),
    path(
        "organizers/<int:organizer_id>/payment-setup-status/",
        PaymentSetupStatusView.as_view(),
        name="organizer-payment-setup-status",
    ),
    path(
        "organizers/<int:organizer_id>/provider-connection-tests/",
        ProviderConnectionTestListCreateView.as_view(),
        name="organizer-provider-connection-tests",
    ),
    path(
        "organizers/<int:organizer_id>/provider-authorization/start/",
        ProviderAuthorizationStartView.as_view(),
        name="organizer-provider-authorization-start",
    ),
    path(
        "organizers/<int:organizer_id>/provider-authorization/callback/",
        ProviderAuthorizationCallbackView.as_view(),
        name="organizer-provider-authorization-callback",
    ),
    path(
        "organizers/<int:organizer_id>/provider-authorization/disconnect/",
        ProviderAuthorizationDisconnectView.as_view(),
        name="organizer-provider-authorization-disconnect",
    ),
    path(
        "organizers/<int:organizer_id>/provider-authorization/replacements/<int:session_id>/confirm/",
        ProviderAccountReplacementConfirmView.as_view(),
        name="organizer-provider-account-replacement-confirm",
    ),
    path(
        "organizers/<int:organizer_id>/trips/",
        TripSetupListCreateView.as_view(),
        name="organizer-trip-setups",
    ),
    path(
        "organizers/<int:organizer_id>/trips/<int:trip_id>/",
        TripSetupDetailView.as_view(),
        name="organizer-trip-setup-detail",
    ),
    path(
        "organizers/<int:organizer_id>/trips/<int:trip_id>/description/",
        TripDescriptionView.as_view(),
        name="organizer-trip-description",
    ),
    path(
        "organizers/<int:organizer_id>/trips/<int:trip_id>/itinerary/",
        TripItineraryView.as_view(),
        name="organizer-trip-itinerary",
    ),
    path(
        "organizers/<int:organizer_id>/trips/<int:trip_id>/media/",
        TripMediaGalleryView.as_view(),
        name="organizer-trip-media",
    ),
    path(
        "organizers/<int:organizer_id>/trips/<int:trip_id>/packages/",
        TripPackageSectionView.as_view(),
        name="organizer-trip-packages",
    ),
    path(
        "organizers/<int:organizer_id>/trips/<int:trip_id>/payment-schedule/",
        TripPaymentScheduleSectionView.as_view(),
        name="organizer-trip-payment-schedule",
    ),
    path(
        "organizers/<int:organizer_id>/trips/<int:trip_id>/confirmation-requirements/",
        TripConfirmationRequirementsSectionView.as_view(),
        name="organizer-trip-confirmation-requirements",
    ),
    path(
        "organizers/<int:organizer_id>/trips/<int:trip_id>/duplicate/",
        TripDuplicateView.as_view(),
        name="organizer-trip-duplicate",
    ),
    path(
        "organizers/<int:organizer_id>/trips/<int:trip_id>/date-change/",
        TripDateChangeView.as_view(),
        name="organizer-trip-date-change",
    ),
    path(
        "organizers/<int:organizer_id>/trips/<int:trip_id>/cancel/",
        TripCancellationView.as_view(),
        name="organizer-trip-cancel",
    ),
    path(
        "organizers/<int:organizer_id>/trips/<int:trip_id>/complete/",
        TripCompletionView.as_view(),
        name="organizer-trip-complete",
    ),
    path(
        "public/organizers/<int:organizer_id>/booking-readiness/",
        PublicBookingReadinessView.as_view(),
        name="public-booking-readiness",
    ),
    path(
        "public/trips/<int:trip_id>/booking-readiness/",
        PublicTripBookingReadinessView.as_view(),
        name="public-trip-booking-readiness",
    ),
    path(
        "public/trips/<slug:organizer_slug>/<slug:trip_slug>/",
        PublicTripDetailView.as_view(),
        name="public-trip-detail",
    ),
    path(
        "public/trips/<slug:organizer_slug>/<slug:trip_slug>/draft-bookings/",
        PublicDraftBookingCreateView.as_view(),
        name="public-draft-booking-create",
    ),
    path(
        "public/trips/<slug:organizer_slug>/<slug:trip_slug>/manual-payments/",
        PublicQrManualPaymentSubmissionView.as_view(),
        name="public-qr-manual-payment-submission",
    ),
    path(
        "public/bookings/<int:booking_id>/payment-attempts/",
        PublicPaymentAttemptCreateView.as_view(),
        name="public-payment-attempt-create",
    ),
    path(
        "public/payment-attempts/<int:payment_attempt_id>/checkout-success/",
        PublicPaymentAttemptCheckoutSuccessView.as_view(),
        name="public-payment-attempt-checkout-success",
    ),
    path(
        "public/payment-attempts/<int:payment_attempt_id>/provider-confirmation/",
        ProviderPaymentConfirmationView.as_view(),
        name="provider-payment-confirmation",
    ),
    path("webhooks/razorpay/", RazorpayWebhookView.as_view(), name="razorpay-webhook"),
    path(
        "portal/<str:token>/",
        TravelerPortalDetailView.as_view(),
        name="traveler-portal-detail",
    ),
    path(
        "portal/<str:token>/traveler-slots/<int:traveler_slot_id>/identity/",
        TravelerPortalTravelerIdentityView.as_view(),
        name="traveler-portal-traveler-identity",
    ),
    path(
        "portal/<str:token>/traveler-slots/<int:traveler_slot_id>/documents/",
        TravelerPortalTravelerDocumentSubmissionView.as_view(),
        name="traveler-portal-traveler-document-submission",
    ),
    path(
        "portal/<str:token>/manual-payments/",
        TravelerPortalManualPaymentSubmissionView.as_view(),
        name="traveler-portal-manual-payment-submission",
    ),
    path(
        "portal/<str:token>/balance-payment-attempts/",
        TravelerPortalBalancePaymentAttemptCreateView.as_view(),
        name="traveler-portal-balance-payment-attempt-create",
    ),
    path(
        "portal/<str:token>/traveler-slots/<int:traveler_slot_id>/travel-logistics/",
        TravelerPortalTravelLogisticsView.as_view(),
        name="traveler-portal-travel-logistics",
    ),
    path(
        "portal/<str:token>/traveler-slots/<int:traveler_slot_id>/emergency-contact/",
        TravelerPortalEmergencyContactView.as_view(),
        name="traveler-portal-emergency-contact",
    ),
    path(
        "portal/<str:token>/traveler-slots/<int:traveler_slot_id>/medical-disclosure/",
        TravelerPortalMedicalDisclosureView.as_view(),
        name="traveler-portal-medical-disclosure",
    ),
]


def _pattern_lookup(names: list[str]) -> list:
    """Return legacy URL patterns by name, preserving the requested order."""

    by_name = {pattern.name: pattern for pattern in urlpatterns}
    missing = [name for name in names if name not in by_name]
    if missing:
        raise ValueError(f"Missing legacy organizer URL patterns: {', '.join(missing)}")

    return [by_name[name] for name in names]


AUTH_AND_SESSION_URLPATTERNS = _pattern_lookup(
    [
        "auth-signup",
        "auth-login",
        "auth-logout",
        "auth-session",
        "organizer-onboarding",
    ]
)

INTERNAL_ADMIN_URLPATTERNS = _pattern_lookup(
    [
        "internal-admin-organizer-list",
        "internal-admin-organizer-detail",
        "internal-admin-assisted-payment-setup",
        "internal-admin-settlement-readiness-confirm",
        "internal-admin-provider-connection-tests",
        "internal-admin-trip-detail",
        "internal-admin-booking-detail",
    ]
)

TRIP_OPERATIONS_URLPATTERNS = _pattern_lookup(
    [
        "operations-dashboard",
        "operator-workflow-access",
        "operations-booking-detail",
        "operations-manual-booking-create",
        "operations-trip-overview",
        "operations-booking-import-create",
        "operations-manual-reminder-create",
        "operations-balance-payment-link-send",
        "operations-announcement-create",
        "operations-trip-operational-export",
        "operations-manual-payment-create",
        "operations-manual-payment-approve",
        "operations-manual-payment-reject",
        "operations-manual-payment-proof-download",
        "operations-booking-adjustment-create",
        "operations-refund-record-create",
        "operations-payment-exception-resolve",
        "operations-booking-cancel",
        "operations-traveler-addition",
        "operations-booking-confirm",
        "operations-booking-unconfirm",
        "operations-traveler-check-in",
        "operations-traveler-no-show",
        "operations-traveler-cancel",
        "operations-traveler-replace",
        "operations-traveler-package-change",
        "operations-booking-access-link-issue",
        "operations-traveler-document-list",
        "operations-traveler-document-review",
        "operations-traveler-document-download",
    ]
)

ORGANIZER_PROFILE_URLPATTERNS = _pattern_lookup([
    "organizer-identity",
])

ORGANIZER_MEDIA_URLPATTERNS = _pattern_lookup([
    "organizer-media",
])

ORGANIZER_TEAM_ACCESS_URLPATTERNS = _pattern_lookup(
    [
        "organizer-team-access",
        "organizer-invitation-resend",
        "organizer-invitation-revoke",
        "organizer-invitation-accept",
    ]
)

ORGANIZER_PAYMENT_URLPATTERNS = _pattern_lookup(
    [
        "organizer-payout-account",
        "organizer-provider-payment-setup",
        "organizer-manual-payment-instructions",
        "organizer-payment-setup-status",
        "organizer-provider-connection-tests",
        "organizer-provider-authorization-start",
        "organizer-provider-authorization-callback",
        "organizer-provider-authorization-disconnect",
        "organizer-provider-account-replacement-confirm",
    ]
)

ORGANIZER_TRIP_URLPATTERNS = _pattern_lookup(
    [
        "organizer-trip-setups",
        "organizer-trip-setup-detail",
        "organizer-trip-description",
        "organizer-trip-itinerary",
        "organizer-trip-media",
        "organizer-trip-packages",
        "organizer-trip-payment-schedule",
        "organizer-trip-confirmation-requirements",
        "organizer-trip-duplicate",
        "organizer-trip-date-change",
        "organizer-trip-cancel",
        "organizer-trip-complete",
    ]
)

TRIP_MARKETING_AND_BOOKING_URLPATTERNS = _pattern_lookup(
    [
        "public-booking-readiness",
        "public-trip-booking-readiness",
        "public-trip-detail",
        "public-draft-booking-create",
        "public-qr-manual-payment-submission",
    ]
)

TRIP_PAYMENT_URLPATTERNS = _pattern_lookup(
    [
        "public-payment-attempt-create",
        "public-payment-attempt-checkout-success",
        "provider-payment-confirmation",
        "traveler-portal-balance-payment-attempt-create",
        "razorpay-webhook",
    ]
)

TRIP_TRAVELER_PORTAL_URLPATTERNS = _pattern_lookup(
    [
        "traveler-portal-detail",
        "traveler-portal-traveler-identity",
        "traveler-portal-traveler-document-submission",
        "traveler-portal-manual-payment-submission",
        "traveler-portal-travel-logistics",
        "traveler-portal-emergency-contact",
        "traveler-portal-medical-disclosure",
    ]
)


# Keep organizers as the compatibility/session/identity host in this phase.
urlpatterns = AUTH_AND_SESSION_URLPATTERNS
