# Generated by Django 5.1.15 on 2026-05-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0043_organizer_identity_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_description', models.TextField(blank=True)),
                ('publication_state', models.CharField(choices=[('draft', 'Draft Organizer Profile'), ('published', 'Published Organizer Profile'), ('archived', 'Archived Organizer Profile')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to='organizers.organizer')),
            ],
            options={
                'ordering': ['organizer__name', 'id'],
            },
        ),
    ]
