# Generated by Django 5.1.15 on 2026-05-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0043_organizer_identity_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_copy', models.TextField(blank=True)),
                ('demand_pattern', models.CharField(blank=True, max_length=260)),
                ('publication_state', models.CharField(choices=[('draft', 'Draft Demand Page'), ('published', 'Published Demand Page'), ('archived', 'Archived Demand Page')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_organizers', models.ManyToManyField(blank=True, related_name='demand_pages', to='organizers.organizer')),
                ('selected_trips', models.ManyToManyField(blank=True, related_name='demand_pages', to='organizers.trip')),
            ],
            options={
                'ordering': ['slug', 'id'],
            },
        ),
    ]
